export const PROJECTS = [
  { slug: "fortune-ecash", href: "/work/fortune-ecash", title: "Fortune eCash App", category: "mobile",
    tags: ["UI/UX", "Fintech", "Research", "Marketing"],
    thumb: { type: "mobile", alt: "Fortune eCash phone mockups" } },
  { slug: "pikabox", href: "/work/pikabox", title: "PikaBox App", category: "mobile",
    tags: ["UI/UX", "Marketplace", "Design System", "Prototyping"],
    thumb: { type: "mobile", alt: "PikaBox mockups" } },
  { slug: "agriflow", href: "/work/agriflow", title: "AgriFlow App", category: "mobile",
    tags: ["UI/UX", "AgriTech", "Field Research", "Localisation"],
    thumb: { type: "mobile", alt: "AgriFlow mockups" } },
  { slug: "advenio", href: "/work/advenio", title: "Advenio Web App", category: "web",
    tags: ["UI/UX", "Hospitality", "Booking", "Prototyping"],
    thumb: { type: "browser", variant: "web", headline: "Find your stay.", lineShort: false, goldTiles: [1, 2], cta: "Book now" } },
  { slug: "mlearn", href: "/work/mlearn", title: "MLearn Web App", category: "web",
    tags: ["UI/UX", "EdTech", "LMS", "Design System"],
    thumb: { type: "browser", variant: "web", headline: "Learn with MLearn.", lineShort: true, goldTiles: [0, 3], cta: "Start a course" } },
  { slug: "toedur", href: "/work/toedur", title: "Toedur Web App", category: "web",
    tags: ["UI/UX", "Education", "Mentorship", "Research"],
    thumb: { type: "browser", variant: "web", headline: "Mentors who get it.", lineShort: false, goldTiles: [1, 2], cta: "Find a mentor" } },
  { slug: "simplia", href: "/work/simplia", title: "Simplia Website", category: "web",
    tags: ["Web Design", "Marketing", "Branding", "SEO"],
    thumb: { type: "browser", variant: "site", headline: "Marketing made simple.", lineShort: true, goldTiles: [0, 3], cta: "Talk to us" } },
  { slug: "chii-neema", href: "/work/chii-neema", title: "Chii Neema Website", category: "web",
    tags: ["Web Design", "Wellness", "Branding", "CMS"],
    thumb: { type: "browser", variant: "site", headline: "Bioresonance therapy.", lineShort: false, goldTiles: [1, 2], cta: "Book a session" } },
  { slug: "tickety", href: "/work/tickety", title: "Tickety Web App", category: "web",
    tags: ["UI/UX", "Events", "Ticketing", "Design System"],
    thumb: { type: "browser", variant: "web", headline: "Tickets, sorted.", lineShort: true, goldTiles: [0, 3], cta: "Get tickets" } },
  { slug: "amarachi", href: "/brand/amarachi", title: "Amarachi Fresh Produce", category: "brand",
    tags: ["Brand Identity", "Logo System", "Packaging", "Colour System"],
    thumb: { type: "monogram", bg: "#1F4227", circle1: "#C7D94F", circle2: "#9CB52F", letter: "A", letterColor: "#C7D94F", wordmark: "AMARACHI", wordmarkColor: "#F7F5EC" } },
  { slug: "everything-riri", href: "/brand/everything-riri", title: "Everything Riri", category: "brand",
    tags: ["Brand Identity", "Packaging Design", "Logo System", "Colour System"],
    thumb: { type: "monogram", bg: "#3B1B2E", circle1: "#E8927C", circle2: "#D0705A", letter: "R", letterColor: "#E8927C", wordmark: "RIRI", wordmarkColor: "#FBF3EF" } },
  { slug: "kindhearts", href: "/brand/kindhearts", title: "Kindhearts Foundation", category: "brand",
    tags: ["Brand Identity", "Non-profit", "Logo System", "Colour System"],
    thumb: { type: "monogram", bg: "#1B3A5C", circle1: "#F0A93B", circle2: "#D18C22", letter: "K", letterColor: "#F0A93B", wordmark: "KINDHEARTS", wordmarkColor: "#F6F4EF" } },
  { slug: "daftari-kenya", href: "/brand/daftari-kenya", title: "Daftari Kenya", category: "brand",
    tags: ["Brand Identity", "Logo System", "Print", "Colour System"],
    thumb: { type: "monogram", bg: "#22304A", circle1: "#E4572E", circle2: "#C3441F", letter: "D", letterColor: "#E4572E", wordmark: "DAFTARI", wordmarkColor: "#F5F3EE" } },
  { slug: "brea-cakes", href: "/brand/brea-cakes", title: "Brea Cakes", category: "brand",
    tags: ["Brand Identity", "Logo System", "Packaging", "Colour System"],
    thumb: { type: "monogram", bg: "#4A2B33", circle1: "#E9B7A5", circle2: "#D0937E", letter: "B", letterColor: "#E9B7A5", wordmark: "BREA", wordmarkColor: "#FCF6F0" } },
  { slug: "posterfolio", href: "/posterfolio", title: "Posterfolio", category: "poster",
    tags: ["Print", "Editorial", "Typography", "Layout"],
    thumb: { type: "posterfolio-preview" } },
  { slug: "logofolio", href: "/logofolio", title: "Logofolio", category: "logo",
    tags: ["Identity", "Marks", "Branding", "Wordmarks"],
    thumb: { type: "logofolio-preview" } },
];

export const FEATURED_SLUGS = ["fortune-ecash", "pikabox", "agriflow"];
